services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: pet-store
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d pet-store"]
      interval: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOSTNAME: postgres
    depends_on:
      postgres:
        condition: service_healthy
