environment: "test"

ktor:
  application:
    modules:
      - org.edu.ApplicationKt.module
  deployment:
    port: 8080

database:
  name: "pet-store"
  user: "user"
  hostname: "localhost"
  port: 5432
  password: "password"
  driver: "org.postgresql.Driver"
  autoCommit: false
  pool:
    max: 10
